spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/db_project
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      maximum-pool-size: 1
#      minimum-idle: 5
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 30000

#  datasource:
#    # Master DB (쓰기용)
#    master:
#      url: jdbc:mariadb://localhost:3306/master
#      username: root
#      password: 1234
#      driver-class-name: org.mariadb.jdbc.Driver
#
#    # Replica DB (읽기용)
#    replica:
#      url: jdbc:mariadb://localhost:3306/replica
#      username: root
#      password: 1234
#      driver-class-name: org.mariadb.jdbc.Driver

# 카프카
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic: test-topic

  batch:
    insert:
      limit: 1000000
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 10000
        order_inserts: true
        order_updates: true

  application:
    name: db_project

  data:
    redis:
      host: localhost
      port: 6379


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      default-receive-queue: test-queue



server:
  port: 8080

logging:
  level:
    com.example.sns_project.batch.aspect: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
