spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/db_project
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 10000
        order_inserts: true
        order_updates: true

  application:
    name: db_project

  data:
    redis:
      host: localhost
      port: 6379


server:
  port: 8080

logging:
  level:
    com.example.sns_project.batch.aspect: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
